// This file is generated by assets/update.ts - DO NOT EDIT MANUALLY
// Run 'bun assets/update.ts' to regenerate this file
// Last generated: 2025-11-06T15:28:19.836Z

import type { FiletypeParserOptions } from "./types"
import { resolve, dirname } from "path"
import { fileURLToPath } from "url"

const moduleDir = dirname(fileURLToPath(import.meta.url))
const resolveAssetPath = (relativePath: string) => resolve(moduleDir, relativePath)

const javascript_highlights = resolveAssetPath("./assets/javascript/highlights.scm")
const javascript_language = resolveAssetPath("./assets/javascript/tree-sitter-javascript.wasm")
const typescript_highlights = resolveAssetPath("./assets/typescript/highlights.scm")
const typescript_language = resolveAssetPath("./assets/typescript/tree-sitter-typescript.wasm")
const markdown_highlights = resolveAssetPath("./assets/markdown/highlights.scm")
const markdown_language = resolveAssetPath("./assets/markdown/tree-sitter-markdown.wasm")
const markdown_injections = resolveAssetPath("./assets/markdown/injections.scm")
const markdown_inline_highlights = resolveAssetPath("./assets/markdown_inline/highlights.scm")
const markdown_inline_language = resolveAssetPath("./assets/markdown_inline/tree-sitter-markdown_inline.wasm")
const zig_highlights = resolveAssetPath("./assets/zig/highlights.scm")
const zig_language = resolveAssetPath("./assets/zig/tree-sitter-zig.wasm")

// Cached parsers to avoid re-resolving paths on every call
let _cachedParsers: FiletypeParserOptions[] | undefined

export function getParsers(): FiletypeParserOptions[] {
  if (!_cachedParsers) {
    _cachedParsers = [
      {
        filetype: "javascript",
        queries: {
          highlights: [javascript_highlights],
        },
        wasm: javascript_language,
      },
      {
        filetype: "typescript",
        queries: {
          highlights: [typescript_highlights],
        },
        wasm: typescript_language,
      },
      {
        filetype: "markdown",
        queries: {
          highlights: [markdown_highlights],
          injections: [markdown_injections],
        },
        wasm: markdown_language,
        injectionMapping: {
          nodeTypes: {
            inline: "markdown_inline",
            pipe_table_cell: "markdown_inline",
          },
          infoStringMap: {
            javascript: "javascript",
            js: "javascript",
            typescript: "typescript",
            ts: "typescript",
            markdown: "markdown",
            md: "markdown",
          },
        },
      },
      {
        filetype: "markdown_inline",
        queries: {
          highlights: [markdown_inline_highlights],
        },
        wasm: markdown_inline_language,
      },
      {
        filetype: "zig",
        queries: {
          highlights: [zig_highlights],
        },
        wasm: zig_language,
      },
    ]
  }
  return _cachedParsers
}
